### ISSUE TITLE
Invalid regular expression error

### ISSUE THREAD

**Issue by buffer** [Kronuz/esprima-python#1]
While attempting to parse jQuery I got this "invalid regular expression" error but was not able to figure out the reason behind it. Thanks

>>> import esprima
>>> import requests
>>> response = requests.get('http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js')
>>> ast = esprima.parse(response.content, {'loc' : True, 'tolerant': True, 'comments' : True})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/esprima/esprima.py", line 76, in parse
    ast = parser.parseModule() if isModule else parser.parseScript()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2865, in parseScript
    body.append(self.parseStatementListItem())
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1558, in parseStatementListItem
    statement = self.parseStatement()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2294, in parseStatement
    statement = self.parseExpressionStatement()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1819, in parseExpressionStatement
    expr = self.parseExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1514, in parseExpression
    expr = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 503, in isolateCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1430, in parseAssignmentExpression
    expr = self.parseConditionalExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1338, in parseConditionalExpression
    expr = self.inheritCoverGrammar(self.parseBinaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1280, in parseBinaryExpression
    expr = self.inheritCoverGrammar(self.parseExponentiationExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1247, in parseExponentiationExpression
    expr = self.inheritCoverGrammar(self.parseUnaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1231, in parseUnaryExpression
    expr = self.inheritCoverGrammar(self.parseUnaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1240, in parseUnaryExpression
    expr = self.parseUpdateExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1201, in parseUpdateExpression
    expr = self.inheritCoverGrammar(self.parseLeftHandSideExpressionAllowCall)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1113, in parseLeftHandSideExpressionAllowCall
    args = self.parseArguments()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 992, in parseArguments
    expr = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 503, in isolateCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1430, in parseAssignmentExpression
    expr = self.parseConditionalExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1338, in parseConditionalExpression
    expr = self.inheritCoverGrammar(self.parseBinaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1280, in parseBinaryExpression
    expr = self.inheritCoverGrammar(self.parseExponentiationExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1247, in parseExponentiationExpression
    expr = self.inheritCoverGrammar(self.parseUnaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1240, in parseUnaryExpression
    expr = self.parseUpdateExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1201, in parseUpdateExpression
    expr = self.inheritCoverGrammar(self.parseLeftHandSideExpressionAllowCall)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1096, in parseLeftHandSideExpressionAllowCall
    expr = self.inheritCoverGrammar(self.parseNewExpression if self.matchKeyword('new') else self.parsePrimaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 608, in parsePrimaryExpression
    expr = self.parseFunctionExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2556, in parseFunctionExpression
    body = self.parseFunctionSourceElements()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2358, in parseFunctionSourceElements
    body.append(self.parseStatementListItem())
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1556, in parseStatementListItem
    statement = self.parseStatement()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2324, in parseStatement
    statement = self.parseVariableStatement()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1803, in parseVariableStatement
    declarations = self.parseVariableDeclarationList(Params(inFor=False))
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1793, in parseVariableDeclarationList
    lst.append(self.parseVariableDeclaration(opt))
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1783, in parseVariableDeclaration
    init = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 503, in isolateCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1430, in parseAssignmentExpression
    expr = self.parseConditionalExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1338, in parseConditionalExpression
    expr = self.inheritCoverGrammar(self.parseBinaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1280, in parseBinaryExpression
    expr = self.inheritCoverGrammar(self.parseExponentiationExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1247, in parseExponentiationExpression
    expr = self.inheritCoverGrammar(self.parseUnaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1240, in parseUnaryExpression
    expr = self.parseUpdateExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1201, in parseUpdateExpression
    expr = self.inheritCoverGrammar(self.parseLeftHandSideExpressionAllowCall)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1096, in parseLeftHandSideExpressionAllowCall
    expr = self.inheritCoverGrammar(self.parseNewExpression if self.matchKeyword('new') else self.parsePrimaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 608, in parsePrimaryExpression
    expr = self.parseFunctionExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2556, in parseFunctionExpression
    body = self.parseFunctionSourceElements()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2358, in parseFunctionSourceElements
    body.append(self.parseStatementListItem())
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1556, in parseStatementListItem
    statement = self.parseStatement()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 2324, in parseStatement
    statement = self.parseVariableStatement()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1803, in parseVariableStatement
    declarations = self.parseVariableDeclarationList(Params(inFor=False))
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1796, in parseVariableDeclarationList
    lst.append(self.parseVariableDeclaration(opt))
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1783, in parseVariableDeclaration
    init = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 503, in isolateCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1430, in parseAssignmentExpression
    expr = self.parseConditionalExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1338, in parseConditionalExpression
    expr = self.inheritCoverGrammar(self.parseBinaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1280, in parseBinaryExpression
    expr = self.inheritCoverGrammar(self.parseExponentiationExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1247, in parseExponentiationExpression
    expr = self.inheritCoverGrammar(self.parseUnaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1240, in parseUnaryExpression
    expr = self.parseUpdateExpression()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1201, in parseUpdateExpression
    expr = self.inheritCoverGrammar(self.parseLeftHandSideExpressionAllowCall)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 1096, in parseLeftHandSideExpressionAllowCall
    expr = self.inheritCoverGrammar(self.parseNewExpression if self.matchKeyword('new') else self.parsePrimaryExpression)
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 522, in inheritCoverGrammar
    result = parseFunction()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 593, in parsePrimaryExpression
    token = self.nextRegexToken()
  File "/usr/local/lib/python2.7/site-packages/esprima/parser.py", line 335, in nextRegexToken
    token = self.scanner.scanRegExp()
  File "/usr/local/lib/python2.7/site-packages/esprima/scanner.py", line 1134, in scanRegExp
    value = self.testRegExp(pattern, flags)
  File "/usr/local/lib/python2.7/site-packages/esprima/scanner.py", line 1040, in testRegExp
    self.throwUnexpectedToken(Messages.InvalidRegExp)
  File "/usr/local/lib/python2.7/site-packages/esprima/scanner.py", line 130, in throwUnexpectedToken
    self.index - self.lineStart + 1, message)
  File "/usr/local/lib/python2.7/site-packages/esprima/error_handler.py", line 67, in throwError
    raise self.createError(index, line, col, description)
esprima.error_handler.Error: Line 2: Invalid regular expression

**Comment by Kronuz** [comment]
Thank you! Should be fixed now in v4.0.0-dev.10

**Comment by buffer** [comment]
I tested the new version and can confirm the issue disappeared. Thanks!
