### ISSUE TITLE
UnicodeDecodeError issue

### ISSUE THREAD

**Issue by buffer** [Kronuz/esprima-python#3]
While parsing the following JS https://www.verizon.com/cs/groups/public/documents/adacct/touchcommeraceatlas.js 

I got the following UnicodeDecodeError

[2017-09-05 15:06:33] [AST] Script parsing error (see trace below)
[2017-09-05 15:06:33] Traceback (most recent call last):
  File "build/bdist.macosx-10.12-intel/egg/thug/AST/AST2.py", line 71, in __init__
    self.__init_ast(script)
  File "build/bdist.macosx-10.12-intel/egg/thug/AST/AST2.py", line 82, in __init_ast
    'comments' : True
  File "build/bdist.macosx-10.12-intel/egg/esprima/esprima.py", line 77, in parse
    parser = Parser(code, options=options, delegate=parserDelegate)
  File "build/bdist.macosx-10.12-intel/egg/esprima/parser.py", line 107, in __init__
    self.scanner = Scanner(code, self.errorHandler)
  File "build/bdist.macosx-10.12-intel/egg/esprima/scanner.py", line 103, in __init__
    self.source = unicode(code) + '\x00'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

**Comment by mszu** [comment]
You'll see these kinds of errors when you (or some library you're using) are trying to treat utf-8 encoded data as something else (ascii encoded bytes, in this case). You haven't posted your actual code here, but try specifying the encoding when you load that JS file:

```python
import esprima
import os

filepath = os.path.expanduser('~/Desktop/verizon.js')

with open(filepath, mode='r', encoding='utf-8') as f:     ## Yes, works as expected
## with open(filepath, mode='r', encoding='ascii') as f:  ## No, shows your error
## with open(filepath, mode='r') as f:                    ## Might work depending on platform?
    print(esprima.parseScript(f.read()))
```

**Comment by Kronuz** [comment]
Yes, you need to pass properly decoded code (unicode) to esprima parser.
